namespace lms.Forms
{
    partial class Form_Guide
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.listBoxGuide = new System.Windows.Forms.ListBox();
            this.SuspendLayout();
            // 
            // listBoxGuide
            // 
            this.listBoxGuide.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.listBoxGuide.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.listBoxGuide.FormattingEnabled = true;
            this.listBoxGuide.ItemHeight = 15;
            this.listBoxGuide.Items.AddRange(new object[] {
            "1111111111222222222233333333334444444444555555555566666666667777777777888888888",
            "",
            "The Damage Formula FAQ for MHP3rd (JP) Version 0.52",
            "Created by Holywoodchuck",
            "",
            "===============================================================================",
            "                                 Changelog",
            "===============================================================================",
            "February 17th, 2011 -- Version 0.52",
            "",
            "February 7th, 2011 -- Version 0.51",
            "Corrected some errors",
            "Separated item damage formula into neutral damage formula",
            "",
            "January 30th, 2011 -- Version 0.50",
            "",
            "",
            "===============================================================================",
            "                                 Table of Contents",
            "===============================================================================",
            "",
            "0A = Introduction and Basics",
            "",
            "1A = Blademaster Damage Formula and Values",
            " 1B = Great Sword",
            " 1C = Sword and Shield",
            " 1D = Lance",
            " 1E = Hunting Horn",
            " 1F = Hammer",
            " 1G = Switch Axe",
            " 1H = Gunlance",
            " 1I = Long Sword",
            " 1J = Dual Swords",
            "",
            "2A = Bow Damage Formula and Values (Under Construction)",
            "",
            "3A = Neutral Damage Formula",
            "",
            "4A = Status Effects and Infliction (Under Construction)",
            " 4B = Poison",
            " 4C = Paralysis",
            " 4D = Sleep",
            " 4E = KO",
            " 4F = Stamina and Exhaust",
            "",
            "5A = Skills, Items, and Miscellaneous (Under Construction)",
            " 5B = Skills",
            " 5C = Item Damage Values",
            " 5D = Miscellaneous",
            "",
            "",
            "=======================================================",
            "0A       Introduction and Basics",
            "=======================================================",
            "",
            "This guide is about the damage formula in Monster Hunter Portable 3rd. The",
            "damage formula is a series of mathematical operations that will tell you how",
            "much damage you do to a monster. I am assuming that you know some basic",
            "understandings of how you deal damage to monsters.",
            "",
            "This guide is for people who want a better understanding of how much damage",
            "they do to a monster. It may not be for everyone.",
            "",
            "",
            "There are three main types of damage: Raw, Element, and Neutral.",
            "",
            "Raw is the type of damage you regularly do from hitting monsters with your",
            "weapon. Raw is also divided into sub-types: Cut, Impact, and Shot.",
            "",
            "Element is the type of damage you regualarly do from hitting monsters with",
            "your weapon with a element. Element is also divided into sub-types: Fire,",
            "Thunder, Water, Ice, and Dragon.",
            "",
            "Neutral is the type of damage that is not affected by where you hit the",
            "monster. One of the main source of Neutral damage is bombs.",
            "",
            "I will be using some terms in this guide.",
            "Int - take the integer of the number, but always round down, You must cut off",
            " decimals and do not alter any other number.",
            "X - Multiply",
            "+ - Add",
            "(E)AU - Specific elemntal attack up +1/2. There are 5 different skills for 5",
            "        different elements.",
            "EAU - Elemental attack up.",
            "LSM - Low sharpness connect modifier. Only applies when the sharpness of the",
            "      weapon is yellow or lower and the attack hits at a certain timing or",
            "      spot on the weapon. Most blademaster weapon attakcks have this, and the",
            "      modifiers are usually 0.60 or 0.70. This modifier is still being tested.",
            "",
            "Universal modifiers:",
            "",
            "Defense modifiers:",
            "Village    - 100%",
            "Guild *1-2 - 100%",
            "Guild *3-5 -  95%",
            "Guild *6   -  80%",
            "Guild *7-8 -  75%",
            "There are exceptions to defense modifiers.",
            "",
            "",
            "Disclaimers: Some of the names of skills, attacks, items, and others, are what",
            "             I thought to be appropriate. They might not be the same as what",
            "             you might think of.",
            "             Even though all values in this guide have been tested multiple",
            "             times in different situations, it is still possible that there are",
            "             errors.",
            "",
            "",
            "=======================================================",
            "1A      Blademaster Damage Formula and Values",
            "=======================================================",
            "",
            "Blademaster damage formula applies to:",
            "Great Sword, Sword and Shield, Lance, Hunting Horn, Hammer, Switch Axe,",
            "Gunlance, Long Sword, and Dual Swords",
            "",
            "The formula:",
            "",
            "[ (ATTACK X MOTION X HITZONE X AFFINITY X SHARP X CONNECT X SPECIAL)",
            " +",
            "  (ELEMENT X EMOTION X EHITZONE X ESHARP X ESKILLS X ESPECIAL) ]",
            " Int",
            " X (DEFENSE X RAGE X STATUS) = Int damage",
            "",
            "ATTACK - Raw attack power shown in the status screen",
            "MOTION - Attack motion value. Refer to tables of each weapon. Remember to put",
            "         decimals.",
            "HITZONE - Value of the specific hitzone. Make sure you have the right type",
            "          (Cut or Impact).",
            "AFFINITY - Critical hit from affinity. If the attack crits, put a 1.25",
            "           modifier. If the attack negative crits, put a 0.75 modifier.",
            "SHARP - Sharpness modifier for raw damage.",
            "CONNECT - Connect modifier. This can change depending on where on your weapon",
            "          you hit with. Most, if not all, blademaster weapons have a connect",
            "          modifier when at yellow or lower sharpness.",
            "SPECIAL - Any special raw modifiers specified. Multiply if there are multiple.",
            "ELEMENT - Elemental value on the weapon. You must put in the original value",
            "          if you have any skills that modifies the displayed value.",
            "EMOTION - Elemental modifier for certain attack motions. This is 100% for most",
            "          attacks, but some weapons have different modifiers.",
            "EHITZONE - Value of the specific hitzone for the element. Make sure you have",
            "           the right type (Fire, Thunder, Water, Ice, or Dragon).",
            "ESHARP - Sharpness modifier for elemental damage.",
            "ESKILLS - Skills that modify elemental value. For (E)AU+1/2, put in",
            "          1.10(for +1) or 1.20(for +2). For EAU, put in 1.10. If you have",
            "          both, you must multiply them, do not add them.",
            "ESPECIAL - Any special elemental modifiers specified. Multiply if there are",
            "           multiple.",
            "DEFENSE - Overall defense for the monster. Varies from quest to quest but are",
            "          usually grouped by quest levels.",
            "RAGE - Modifier when the monster is enraged. Not all monsters have this.",
            "STATUS - Modifier when the monster is affected by paralysis or sleep. For",
            "         sleep, put in 2.00 or 3.00. For paralysis, put in 1.05 or 1.10.",
            "         Refer to their own sections in Status Effects.",
            "damage - the damage you will do to the monster.",
            "",
            "If the attack hits multiple times, you must calculate the damage of each hit.",
            "",
            "Sharpness modifiers:",
            "Color      Raw     Element",
            "Red        0.50    0.25",
            "Orange     0.75    0.50",
            "Yellow     1.00    0.75",
            "Green      1.05    1.00",
            "Blue       1.20    1.0625",
            "White      1.32    1.125",
            "",
            "",
            "",
            "--------------------------------------------",
            "|1B        Great Sword*                    |",
            "|------------------------------------------|",
            "| Attack Motion        |Value(%)|Element(%)|",
            "|==========================================|",
            "| Down slash           |   48   |   100    |",
            "| Up swing             |   46   |   100    |",
            "| Side slash           |   36   |   100    |",
            "| Slap**               |   18   |   100    |",
            "| Charge 1             | 65X1.1 |   120    |",
            "| Charge 2             | 80X1.2 |   150    |",
            "| Charge 3             | 100X1.3|   200    |",
            "| S Charge 0           |   52   |   100    |",
            "| S Charge 1           | 72X1.1 |   180    |",
            "| S Charge 2           | 90X1.2 |   225    |",
            "| S Charge 3           | 120X1.3|   300    |",
            "--------------------------------------------",
            "|* Great Sword does all Cut damage except for 1 attack. Every attack gets a",
            "|  0.70 LSM when hitting near the hilt or being too close. Every attack gets",
            "|  a 1.05 connect modifier when hitting near the middle of the weapon.",
            "|  Special elemental modifier also applies to status.",
            "|** Slap does Impact damage and 22 KO",
            "",
            "",
            "",
            "--------------------------------------------",
            "|1C        Sword and Shield                |",
            "|------------------------------------------|",
            "| Attack Motion        |Value(%)|   LSM    |",
            "|==========================================|",
            "| Jumping slash *      |   17   |   0.60   |",
            "| Rising slash *       |   14   |   ?      |",
            "| Down slash combo 1 * |   14   |   0.60   |",
            "| Down slash combo 2 * |   13   |   0.60   |",
            "| Shield combo 1 **    |   10   |   ?      |",
            "| Shield combo 2 *     |   20   |   ?      |",
            "| Shield bash 1 **     |    8   |   0.60   |",
            "| Shield bash 2 **     |   14   |   0.60   |",
            "| Side sweep 1 *       |   21   |   0.60   |",
            "| Side sweep 2 *       |   17   |   0.60   |",
            "| Spin slash *         |   24   |   0.70   |",
            "| Guard slash *        |   14   |   ?      |",
            "--------------------------------------------",
            "| * All attacks with the blade do Cut damage, have a 1.06 special raw modifier",
            "|   and have a 0.70 elemental/status modifier.",
            "| ** All attacks with the shield do Impact damage and have a 0.00 elemental/",
            "|    status modifier. Scombo1 and Sbash2 do 15 KO. Sbash1 does 10 KO.",
            "",
            "",
            "",
            "--------------------------------------------",
            "|1D            Lance                       |",
            "|------------------------------------------|",
            "| Attack Motion        |Value(%)|   LSM *  |",
            "|==========================================|",
            "| Unsheathe            |   27   |   0.70   |",
            "| Low stab 1,2         |   20   |   0.60   |",
            "| Low stab 3           |   27   |   0.60   |",
            "| High stab 1,2        |   22   |   0.60   |",
            "| High stab 3          |   27   |   0.60   |",
            "| Side sweep           |   20   |   0.70   |",
            "| Guard stab           |   14   |   ?      |",
            "| Cancel stab          |   22   |   0.60   |",
            "| Counter low stab     |   20   |   0.60   |",
            "| Counter high stab    |   22   |   0.60   |",
            "| Charged stab         |   50   |   0.60   |",
            "| Charge **            |   16   |   0.60   |",
            "| Charge finisher      |   40   |   ?      |",
            "| Shield bash ***      |   14   |   0.60   |",
            "--------------------------------------------",
            "| All attacks with the lance do Cut damage, except for 1 attack.",
            "| Attacks with the lance, except shield bash, will get a 0.72 special modifier",
            "| and uses Impact hitzone, if the value of Impact hitzone X 0.72 is greater",
            "| than the value of Cut hitzone.",
            "| * All attacks with 0.70 LSM get the modifier when not hitting near the tip",
            "|   of the weapon. Most attacks with 0.60 LSM get the modifier when hitting at",
            "|   the tip of the weapon.",
            "| ** Charge always gets the 0.60 LSM at yellow or lower sharpness. Charge hits",
            "|    get 0.50 elemental/status modifier.",
            "| *** Shield bash always gets the 0.60 LSM at yellow or lower sharpness.",
            "|     Shield bash does impact damage, 27 KO, and 0.00 elemental/status",
            "|     modifier.",
            "",
            "",
            "",
            "----------------------------------------------------",
            "|1E            Hunting Horn                        |",
            "|--------------------------------------------------|",
            "| Attack Motion            |Value(%)|   KO   | LSM |",
            "|==================================================|",
            "| Forward slam             |   33   |   20   | 0.70|",
            "| Left swing               |   30   |   20   | 0.70|",
            "| Right swing              |   30   |   20   | 0.70|",
            "| Hilt stab *              |   10   |    0   | 0.70|",
            "| Backward attack          |   45   |   25   | 0.70|",
            "| 2 hit pound              |  15+45 |  5+15  | 0.70|",
            "| Recital                  |   35   |   22   | 0.70|",
            "| Recital (frm 2hit, slam) |   20   |   15   | ?   |",
            "| Recital (from stab)      |   25   |   22   | ?   |",
            "| Recital (from backward)  |   30   |   25   | ?   |",
            "| Left/Right chain recital |   35   |   22   | 0.60|",
            "| Back chain recital       |  40+30 |  25+25 | ?   |",
            "| Left/Right chain recital+|  33+35 |  22+22 | ?   |",
            "| Back chain recital+      |33+40+30|22+25+25| ?   |",
            "----------------------------------------------------",
            "| All attacks with the hunting horn do Impact damage, except for 1 attack.",
            "| * Hilt stab does Cut damage.",
            "",
            "",
            "",
            "------------------------------------------------",
            "|1F               Hammer                       |",
            "|----------------------------------------------|",
            "| Attack Motion            | Value(%) |   KO   |",
            "|==============================================|",
            "| Unsheathe                |    20    |   15   |",
            "| Pound 1                  |    42    |   15   |",
            "| Pound 2                  |    20    |   15   |",
            "| Golf swing               |    90    |   50   |",
            "| Side slap                |    15    |   22   |",
            "| Charge 1                 |   25+20  |  15+15 |",
            "| Charge 2                 |    40    |   40   |",
            "| Charge pound             |   15+76  |   5+27 |",
            "| Charge spin short        |20+10X2+60| 2X3+40 |",
            "| Charge spin long *       |20+10X4+90| 2X5+50 |",
            "| Charge spin over         |20+10X4+40| 2X5+20 |",
            "------------------------------------------------",
            "| All attacks with the hammer do Impact damage. Most attacks have a LSM of",
            "| 0.60 and/or 0.70 at yellow or lower sharpness.",
            "| * The 10 value from charge spin long can hit 3-4 times, depending on when the",
            "|   finishing input is pressed.",
            "",
            "",
            "",
            "--------------------------------------------",
            "|1G           Switch Axe                   |",
            "|------------------------------------------|",
            "| Attack Motion        |Value(%)|   LSM    |",
            "|==========================================|",
            "|        Axe mode                          |",
            "| Side slash           |   23   |   0.70   |",
            "| Overhead slash       |   46   |   0.60   |",
            "| Up swing             |   32   |   ?      |",
            "| Forward stab         |   19   |   0.60   |",
            "| Right/Left swing *   |   24   |   0.60   |",
            "|       Sword mode **                      |",
            "| Down slash           |   32   |   0.70   |",
            "| Rising slash         |   28   |   0.70   |",
            "| Side slice           |   22   | 0.60/0.70|",
            "| Burst opener *       |   28   |   0.60   |",
            "| Burst hit *          |  13X7  |   0.60   |",
            "| Burst finisher ***   |   80   |   ?      |",
            "| Burst cancel finisher|   50   |   ?      |",
            "--------------------------------------------",
            "| All attacks with the switch axe do Cut damage.",
            "| * Right/Left swing, burst opener, and burst hits always have a LMS of 0.60",
            "|   at yellow or lower sharpness.",
            "| ** While in sword mode, the phial on the switch axe activates. With power",
            "|    phial, put a special raw modifier of 1.20. With elemental/status+ phial,",
            "|    put a special elemental modifier of 1.25. Every other phial has a specific",
            "|    value for each switch axe.",
            "| *** Burst finisher and burst cancel finisher do Cut damage, but does not",
            "|     affect tail cutting tolerance.",
            "",
            "",
            "",
            "---------------------------------------",
            "|1H           Gunlance                |",
            "|-------------------------------------|",
            "| Attack Motion        |Value(%)| LSM |",
            "|=====================================|",
            "| Rising step slash    |   32   | ?   |",
            "| Rising slash         |   28   | ?   |",
            "| Guard stab           |   18   | ?   |",
            "| Low stab             |   24   | 0.60|",
            "| Slam                 |   40   | ?   |",
            "---------------------------------------",
            "| All weapon attacks with the gunlace do Cut damage.",
            "| Please refer to Neutral Damage Formula for the damage formula of",
            "| shelling and wyvern fire.",
            "| Charged shells get a special neutral modifier of 1.20 except spread type,",
            "| which get a special neutral modifier of 1.45.",
            "| Full burst get a special neutral modifier of 1.10 for normal, 1.00 for long, ",
            "| and 0.90 for spread.",
            "| Wyvern Fire get a special neutral modifier of 1.20 only for long.",
            "================================",
            "| Shelling                     |",
            "| Type / Level| Neutral | Fire |",
            "| Normal 1    |    10   |   4  |",
            "| Normal 2    |    14   |   5  |",
            "| Normal 3    |    18   |   6  |",
            "| Normal 4    |    21   |   7  |",
            "--------------------------------",
            "| Long   1    |    15   |   9  |",
            "| Long   2    |    21   |  11  |",
            "| Long   3    |    28   |  14  |",
            "| Long   4    |    32   |  16  |",
            "--------------------------------",
            "| Spread 1    |    20   |   6  |",
            "| Spread 2    |    30   |   8  |",
            "| Spread 3    |    40   |  10  |",
            "| Spread 4    |    44   |  11  |",
            "--------------------------------",
            "==========================",
            "| Wyvern Fire            |",
            "| Level | Neutral | Fire |",
            "|    1  |   30X4  | 10X4 |",
            "|    2  |   35X4  | 11X4 | ",
            "|    3  |   40X4  | 12X4 |",
            "|    4  |   45X4  | 13X4 |",
            "--------------------------",
            "",
            "",
            "---------------------------------",
            "|1I           Long Sword        |",
            "|-------------------------------|",
            "| Attack Motion        |Value(%)|",
            "|===============================|",
            "| Down slash 1         |  26    |",
            "| Down slash 2         |  23    |",
            "| Stab                 |  14    |",
            "| Up slice *           |  18    |",
            "| Sweep *              |  24    |",
            "| Empty spirit slash * |  16    |",
            "| Spirit slash 1 *     |  28    |",
            "| Spirit slash 2 *     |  30    |",
            "| Spirit slash 3 *     |12+14+34|",
            "| Spirit spin slash *  |  42    |",
            "---------------------------------",
            "| All attacks with the long sword do Cut damage.",
            "| Once the gauge is filled, there is a temporary special raw modifier of 1.13.",
            "| Special raw modifier for gauge color: White 1.05, yellow 1.10, red 1.20",
            "| * Up slice, sweep, and all spirit slash attacks have a connect modifier of",
            "|   1.05 when hit near the middle of the weapon.",
            "",
            "",
            "",
            "----------------------------------------------------------------",
            "|1J           Dual Swords                                      |",
            "|--------------------------------------------------------------|",
            "| Attack Motion             |    Value(%)    |  Element(%) *   |",
            "|==============================================================|",
            "|   Regular mode                                               |",
            "| /\\O Charging swipe        | 7 up to 4 hits | 49 up to 4 hits |",
            "|  /\\ Up slice              |      18        |       70        |",
            "| /\\ Side swipe             |     10+13      |      70+70      |",
            "|  /\\ Spin swipe            |    10+12+12    |     70+70+70    |",
            "|   /\\ Hand wheel slash     |    12+14+14    |     70+49+49    |",
            "| O Right slice             |      9+12      |      70+70      |",
            "| LO Left slice             |     10+13      |      70+70      |",
            "| O Right/Left spin 1       |    16+6+8      |     70+70+70    |",
            "|    Right/Left spin 2      |    18+6+10     |     70+70+70    |",
            "| Mini demon dance          |    8X4+20+20   |    70X4+49+49   |",
            "|   Demonized Mode **                                          |",
            "| /\\ Hand wheel slash       |    12+14+14    |     70+49+49    |",
            "|  /\\ Six step slash        | 6+8+6+8+14+14  |    70X4+49+49   |",
            "| O Right/Left spin 1       |    18+6+10     |     70+70+70    |",
            "|    Right/Left spin 2      |    16+6+8      |     70+70+70    |",
            "|   Charging swipe          | 7 up to 4 hits | 49 up to 4 hits |",
            "|    Up slice               |      18        |       70        |",
            "| Demon dance               |  29+4X8+18+18  |  70+70X8+49+49  |",
            "----------------------------------------------------------------",
            "| All attacks with the dual swords do Cut damage.",
            "| * Elemental modifiers are still being tested.",
            "| ** Put a special raw modifier of 1.15 in demonized mode.",
            "",
            "",
            "",
            "=======================================================",
            "2A    Bow Damage Formula and Values (Under Construction)",
            "=======================================================",
            "",
            "Disclaimer: Bow damage formula and values are still being tested. All",
            "            information here are what initial and limited tests showed.",
            "",
            "The formula:",
            "",
            "[ (ATTACK X ARROW X HITZONE X AFFIN X RCHARGE X DIST X SKILL X SPECIAL)",
            " +",
            "  (ELEMENT X EHITZONE X ECHARGE X ESKILLS X ESPECIAL) ]",
            " Int",
            " X (DEFENSE X RAGE X STATUS) = Int damage",
            "",
            "",
            "ATTACK - Raw attack power shown in the status screen",
            "ARROW - Value of the arrow. Refer to arrow tables.",
            "HITZONE - Value of the specific hitzone. Make sure you use shot hitzone.",
            "AFFIN - Critical hit from affinity. If the attack crits, put a 1.25",
            "           modifier. If the attack negative crits, put a 0.75 modifier.",
            "RCHARGE - Raw charge modifier. Refer to charge table.",
            "DIST - Distance modifier. Refer to arrow tables for value.",
            "SKILL - Skill modifier. There are 3 types that only affects specific arrows.",
            "        Refer to Skills section.",
            "SPECIAL - Any special raw modifiers specified. Multiply if there are multiple.",
            "ELEMENT - Elemental value on the weapon. You must put in the original value",
            "          if you have any skills that modifies the displayed value.",
            "EHITZONE - Value of the specific hitzone for the element. Make sure you have",
            "           the right type (Fire, Thunder, Water, Ice, or Dragon).",
            "ECHARGE - Elemental charge modifier. Refer to charge table.",
            "ESKILLS - Skills that modify elemental value. For (E)AU+1/2, put in",
            "          1.10(for +1) or 1.20(for +2). For EAU, put in 1.10. If you have",
            "          both, you must multiply them, do not add them.",
            "ESPECIAL - Any special elemental modifiers specified. Multiply if there are",
            "           multiple.",
            "DEFENSE - Overall defense for the monster. Varies from quest to quest but are",
            "          usually grouped by quest levels.",
            "RAGE - Modifier when the monster is enraged. Not all monsters have this.",
            "STATUS - Modifier when the monster is affected by paralysis or sleep. For",
            "         sleep, put in 2.00 or 3.00. For paralysis, put in 1.05 or 1.10.",
            "         Refer to their own sections in Status Effects.",
            "damage - the damage you will do to the monster.",
            "",
            "",
            "Charge table:",
            "-----------------------------------------",
            "| Charge level | Raw | Element | Status |",
            "| Charge 1     |     |         |        |",
            "| Charge 2     |     |         |        |",
            "| Charge 3     |     |         |        |",
            "| Charge 4     |     |         |        |",
            "-----------------------------------------",
            "",
            "Shot tables:",
            "",
            "Distance is counted in rolls",
            "",
            "-----------------------",
            "| Rapid |    Arrow    |",
            "| LVL 1 |             |",
            "| LVL 2 |             |",
            "| LVL 3 |             |",
            "| LVL 4 |             |",
            "| LVL 5 |             |",
            "-----------------------",
            "",
            "------------------------",
            "| Pierce |    Arrow    |",
            "| LVL 1  |             |",
            "| LVL 2  |             |",
            "| LVL 3  |             |",
            "| LVL 4  |             |",
            "| LVL 5  |             |",
            "------------------------",
            "",
            "-------------------------",
            "| Spread |    Arrow     |",
            "| LVL 1  |              |",
            "| LVL 2  |              |",
            "| LVL 3  |              |",
            "| LVL 4  |              |",
            "| LVL 5  |              |",
            "-------------------------",
            "",
            "Arrow rain:",
            "---------------------------",
            "|    Type    |    Arrow   |",
            "| Focused    |            |",
            "| Scattered  |            |",
            "| Blast      |            |",
            "---------------------------",
            "",
            "",
            "",
            "=======================================================",
            "3A      Neutral Damage Formula",
            "=======================================================",
            "",
            "",
            "The formula:",
            "[(NEUTRAL X NSKILL X NSPECIAL) + (ELEMENT X EHITZONE X NESKILL X ESPECIAL)]",
            " X (GSHARP)",
            " int",
            " X (DEFENSE X RAGE X STATUS) = Int (damage)",
            "",
            "NEUTRAL - Neutral damage value.",
            "NSKILL - Any skill that affects neutral damage from the specific source.",
            "NSPECIAL - Special modifier for neutral damage.",
            "ELEMENT - Element value.",
            "EHITZONE - Value of the specific hitzone for the element. Make sure you have",
            "           the right type (Fire, Thunder, Water, Ice, or Dragon).",
            "NESKILL - Any skill that affects elemental damage from the specific source.",
            "          EAU and (E)AU+1/2 does not affect this.",
            "ESPECIAL - Special modifier for elemental damage.",
            "GSHARP - Gunlance sharpness modifier. Only applies to gunlance shells. Put",
            "         0.75 at orange sharpness and 1.00 for yellow and higher.",
            "DEFENSE - Overall defense for the monster. Varies from quest to quest but are",
            "          usually grouped by quest levels.",
            "RAGE - Modifier when the monster is enraged. Not all monsters have this.",
            "STATUS - Modifier when the monster is affected by paralysis or sleep. For",
            "         sleep, put in 2.00 or 3.00. For paralysis, put in 1.05 or 1.10.",
            "         Refer to their own section in Status Effects.",
            "damage - the damage you will do to the monster.",
            "",
            "This formula applies to gunlance shells, gunlance wyvern fire, most damage ",
            " dealing items, and kick.",
            "",
            "",
            "",
            "=======================================================",
            "4A  Status Effects and Infliction (Under Construction)",
            "=======================================================",
            "",
            "Every monster has a certain tolerance to each status effects. Once you store",
            "enough status value to go over the tolerance, the status is inflicted on the",
            "monster.",
            "",
            "",
            "----------------------",
            "4B     Poison",
            "----------------------",
            "",
            "Poison deals damage to the monster. The amount of damage, overall time, and",
            "damage period varies from monster to monster.",
            "",
            "",
            "----------------------",
            "4C    Paralysis",
            "----------------------",
            "",
            "Paralysis immobilize the monster. The duration varies from monster to monster.",
            "Attacks against paralized monster get a status modifier.",
            "For village/low rank monsters, the status modifier is 1.10.",
            "For high rank monsters, the status modifier is 1.05.",
            "",
            "",
            "----------------------",
            "4D    Sleep",
            "----------------------",
            "",
            "Sleep puts the monster to sleep, immobilizing the monster until it is damaged",
            "or wakes up on its own. The duration varies from monster to monster.",
            "The single damage that wakes the monster up gets a status modifier.",
            "For most blademaster attacks, the status modifier is 2.00.",
            "For most item damages, the status modifier is 3.00.",
            "Sleep status modifier for gunner attacks are still being tested.",
            "",
            "",
            "----------------------",
            "4E    KO",
            "----------------------",
            "",
            "Not truly considered as a status effect. KO immobilizes the monster. The",
            "duration varies from monster to monster.",
            "",
            "",
            "----------------------",
            "4F Stamina and Exhaust",
            "----------------------",
            "",
            "Not truly considered as a status effect. Once reaching the tolerance, the",
            "monster is staggered in a special way, and loses stamina.",
            "",
            "",
            "",
            "=======================================================",
            "5A  Skills, Items, and Miscellaneous (Under Construction)",
            "=======================================================",
            "",
            "----------------------",
            "5B  Skills",
            "----------------------",
            "",
            "Here are the skills that affect the damage formula:",
            "",
            "(Elemental) attack up +1/2 - Adds an elemental modifier of 1.10/1.20.",
            "",
            "Elemental attack up - Adds an elemental modifier of 1.10.",
            "",
            "Bomber - Adds a neutral skill modifier of 1.30 only for bombs.",
            "",
            "Gunnery 1/2 - Add a neutral skill modifier of 1.10/1.20 for gunlace shells",
            "              and gunlance wyvern fire.",
            "",
            "",
            "----------------------",
            "6C  Item Damage Values",
            "----------------------",
            "",
            "Refer to Neutral Damage Formula.",
            "",
            "-----------------------------------------------",
            "|     Item     |Neutral|  Element  |  Status  |",
            "| Small bomb   |   20  |      0    |     0    |",
            "| Rocket bomb  |   20  |      0    |     0    |",
            "| Felvine bomb |    0  |      0    |  felvine |",
            "| Large bomb   |   80  |      0    |     0    |",
            "| Large bomb G |  150  |      0    |     0    |",
            "| JUMP bomb    |   80  |      0    |     0    |",
            "| Politan bomb |   80  | 50 Thunder|     0    |",
            "|Throwing knife|   20  |      0    |     0    |",
            "| Poison knife |    5  |      0    | 50 Poison|",
            "|  Para knife  |    5  |      0    | 50 Para  |",
            "|  Sleep knife |    5  |      0    | 50 Sleep |",
            "| Tranq knife  |    0  |      0    |   Tranq  |",
            "|  Boomerang * |    8  |      0    |     0    |",
            "|  Ballista    |  40X2 |      0    |     0    |",
            "|  Cannon      |   170 |      0    |     0    |",
            "| Binder shot  |    1  |      0    |     0    |",
            "| Anti-D bomb  |   400 |      0    |     0    |",
            "| Supply bomb  |   150 |      0    |     0    |",
            "------------------------------------------------",
            "| * Boomerang affects tail cutting tolerance.",
            "",
            "",
            "----------------------",
            "6D  Miscellaneous",
            "----------------------",
            "",
            "Kick deals 2 neutral damage.",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "Credits:",
            "Most tests were based on values taken from various sources.",
            "Some of the sources are:",
            "MHP3rd JP wiki",
            "2ch",
            "Special Thanks to everyone who contributed to this FAQ, the wiki, and any",
            "other website with MHP3rd data.",
            "Thank you to the people who made the tools and codes to make the tests much",
            " easier.",
            "",
            "Created by Holywoodchuck",
            "Suggestions, feedbacks, questions, problems, etc?",
            "Contact: holywoodchuck@hotmail.com",
            "",
            "",
            "No Copyright",
            "You can use this guide in any way you want to.",
            "Give credits where they belong."});
            this.listBoxGuide.Location = new System.Drawing.Point(12, 12);
            this.listBoxGuide.Name = "listBoxGuide";
            this.listBoxGuide.Size = new System.Drawing.Size(776, 407);
            this.listBoxGuide.TabIndex = 0;
            // 
            // Form_Guide
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.listBoxGuide);
            this.Name = "Form_Guide";
            this.Text = "Form_Guide";
            this.ResumeLayout(false);

        }

        #endregion

        private ListBox listBoxGuide;
    }
}